#!/usr/bin/env bash

. $(dirname "$0")/common.sh

cd "$HOME"

cat "$ROOT"/list | while read name; do
  src="$ROOT"/$name
  dst=.$name
  echo "$name: adding $dst"
  [ -e "$src" ] || {
    echo "$name: missing source file: $src" >&2
    continue
  }
  [ ! -e "$dst" ] || {
    echo "$name: already existing destination file: $dst" >&2
    continue
  }
  ln -v -s "$src" "$dst"
done

# bash
echo "bash: installing"
ln -v -s .bash_profile .bashrc

# tmux
echo "tmux: installing"
ln -v -s .tmux/tmux.conf .tmux.conf

# Neovim
echo "Neovim: linking to Vim config"
ln -v -s .vimrc .nvimrc

# Vim
echo "Vim: installing"
mkdir -v -p .vim/{bundle,swap}
[ -d .vim/bundle/vundle/.git ] || {
  git clone https://github.com/gmarik/vundle .vim/bundle/vundle || {
    echo "Vim: failed to clone 'vundle'" >&2
    exit 1
  }
}
vim +BundleInstall +BundleClean +qa || {
  echo "Vim: failed to install vundle bundles" >&2
  exit 1
}
