#!/usr/bin/env bash

. $(dirname "$0")/common.sh

cd "$HOME"

cat "$ROOT"/list | while read name; do
  f=.$name
  echo "$name: removing $f"
  rm -v "$f"
done

# tmux
echo "tmux: uninstalling"
rm -v .tmux.conf

# fish
echo "fish: uninstalling"
dst=.config/fish
rm -v "$dst"/config.fish
rm -v "$dst"/functions

# Neovim
echo "Neovim: unlinking from Vim config"
rm -v .nvimrc

# Vim
echo "Vim: uninstalling"
rm -v -rf .vim
