#!/usr/bin/env bash

. $(dirname "$0")/common.sh

cd "$HOME"

cat "$ROOT"/list | while read name; do
  f=.$name
  echo "$name: removing $f"
  rm -v "$f"
done

# bash
echo "bash: uninstalling"
rm -v .bashrc

# tmux
echo "tmux: uninstalling"
rm -v .tmux.conf

# Neovim
echo "Neovim: unlinking from Vim config"
rm -v .nvimrc

# Vim
echo "Vim: uninstalling"
rm -v -rf .vim
